name: test
on: [push]

jobs:
  test:
    runs-on: ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest
    steps:
      - uses: actions/checkout@v4

      - name: build and test
        shell: bash
        run: |
          set -e

          # ROS 2 の setup.bash は set -u と相性が悪いので、source中だけ nounset を無効化
          set +u
          source /opt/ros/humble/setup.bash
          set -u

          rsync -av ./ /root/ros2_ws/src/sysinfo_pub/
          cd /root/ros2_ws
          bash -xv ./src/sysinfo_pub/test/test.bash /root
